### ISSUE TITLE
VR-button should exit VR as well as enter

### ISSUE THREAD

**Issue by jpryne** [makepad/makepad#110]
I just tried Makepad in VR and... WOW! It was so much more immediately accessible what was happening with the "treeworld"-demo. I did find myself wanting a few things to be added: a virtual keyboard, a way to grab the code-window by the edges and stretch it to a bigger size, fatter scrollbars, tabs that can be popped out into virtual screens of their own.. lots of ideas, really. (Should I open issues for each of these?)

In any case, I think one of the fundamental rules of UI design is this: Always give the user a way out.
So, how about making that useless-in-vr vr-button a different function when in vr? It should *exit* vr.

**Comment by makepaddev** [comment]
Hi! Yea we are also very happy about how the VR mode turned out!.

Right now making VR better isn't a priority, we are building a visual UI designer. Your ideas are very valid, and all of them are on the list to improve.
VR mode will definitely be in the UI designer/online tool as part of the package so then we'll improve it.

Till then see it as a nice teaser.
