### ISSUE TITLE
Master currently fails to compile on Linux

### ISSUE THREAD

**Issue by BartMassey** [makepad/makepad#139]
Debian latest, `rustc` nightly 2022-07-04. Trying to compile just the makepad` workspace on `master` fails with many errors in render code. Other public branches and other workspaces also seem to fail or warn for various reasons. Here is a representative error:

```text
error: reference to packed field is unaligned
  --> render/src/drawquad.rs:20:21
   |
20 |             shader: self.shader.clone(),
   |                     ^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[deny(unaligned_references)]` on by default
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #82523 <https://github.com/rust-lang/rust/issues/82523>
   = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
   = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)
```

While there's a lot of these, they look reasonably easy to fix. Would it be useful for me to do this and PR the result, along with cleaning up a bunch of other warnings? Or am I looking at an old version of the product or something?

Thanks much for any info you can provide.

(P.S. — As the architect of XCB, not sure why you're using Xlib here :slightly_smiling_face: . Just kidding though: by all means use whichever you like.)

**Comment by makepaddev** [comment]
Hi,

You are looking at an old version.
The master and dev branch are currently about 1-2 years behind the 'live' branch in terms of code meaning these haven't been kept working with the Rust compiler updates (thats recent), since we really don't want external use yet. 
The complexity of the system is the shader compiler + live coding DSL and this has been evolving tremendously for the last 2 years changing every aspect of the system to the point that teaching people anything about it has been meaningless. 

We have been working on the live branch, but the drag of pulling 3 extra platforms along whilst reworking the system so extensively was too much so we left those temporarily behind, meaning only macos compiles atm on live. 

We are gearing up for a proper supported, and versioned push to crates.io in about three months, at which point all the platforms will work again as well.
I will comment on this issue when that happens

As for XCB i wasn't even aware of it, my home platforms are windows/macos. I'll make sure to investigate it when i'll fix up the linux layer again.
We just made it work as we googled our way through APIs. 

- Makepad team

**Comment by makepaddev** [comment]
And yea we could probably relatively quickly fix up the compiler issues so it atleast builds again. I'll think about it.

**Comment by BartMassey** [comment]
Makes sense, thanks! Let me know if/when you want some help with the Linux version.

**Comment by makepaddev** [comment]
Work on the linux build has started again. I expect it to compile in a few days.

**Comment by BartMassey** [comment]
Sweet! Look forward to trying this stuff.

**Comment by makepaddev** [comment]
Still have to do audio apis but its starting to boot:
https://github.com/makepad/makepad/commit/ce46302688e662dce0f0fa6014e72acf073c8f9a

**Comment by makepaddev** [comment]
it should build now

**Comment by BartMassey** [comment]
Thanks! Yes, `master` builds cleanly. The resulting Ironfish GUI is quite pretty. Some functions don't seem to work yet, and the audio output is heavily clipped for some reason, and it dumps core at exit: I'm sure these will all be fixed soon. Great to see Linux support.
