### ISSUE TITLE
UI Toolkit crate

### ISSUE THREAD

**Issue by gxtaillon** [makepad/makepad#20]
Hello,

I just discovered this project through : https://makepad.github.io/makepad/ and it's wonderfully fast. The description in the readme is interesting and I would like to know if there are plans to create a distinct UI toolkit crate/library that could be used as alternative to spinning up a React/Node server for frontends to rust applications.

Best!

**Comment by makepaddev** [comment]
Hi thanks for your interest, in a few weeks/months makepad will turn into a whole bunch of crates.io crates where it forms a native UI kit as well as a web one. However i'm not sure if we'll turn into 'react/node' for quite some time. We are currently developing the product ideas (aka business) of what makepad will become. Will update readme/maybe this issues with that.

**Comment by gxtaillon** [comment]
I'd be interested to help if you're looking for contributions.

**Comment by makepaddev** [comment]
Hi, not yet. We first want a CLA and be closer to release. This repo + structure is going to be completely different in a few weeks. Then we'll work towards release, so having external contributions isn't very practical right now. Feel of course free to think of what you would want, and do let us know what that is because it might just be added soon or it could cause us to change priorities somewhat. Also if you accept the AS IS you can do whatever with the code right now.
