### ISSUE TITLE
makepad on iOS

### ISSUE THREAD

**Issue by rsaccon** [makepad/makepad#22]
I am tinkering with makepad, wanna make it run on an iPad. So far I have setup the build system for a minimal iOS app (just printing "hello world" on the Xcode console) written in Rust, similar as it is done in [winit](https://github.com/rust-windowing/winit) 

Is there a plan to add support for iOS  ?  If not, here is how I think to mess around with the codebase to make it work on iOS:

- in `cx.rs` I define a new non-desktop `PlatformType` called `IOS`
- I add a file `cx_ios.rs` which is initially mostly just a duplicate of `cx_macos.rs`, but imports from `cx_cocoa_ios`
- In `cx_cocoa_ios.rs` I do things the iOS way, e.g. using `UIKit` instead of `AppKit` and also the font loading or file loading in general needs to be implemented differently. 

Does any of this make sense ? (I am aware that you are not ready yet for accepting external contributions and the codebase might unpredictable change anytime)

**Comment by makepaddev** [comment]
That sounds like the right way to do things. I really try to never abstract in platforms just move some code into shared bits if it really makes sense. We will have a CLA, but not just yet maybe in  2 months. We don't have plans to support iOS just yet, but i did do the whole native metal thing with iOS in mind and it sounds great if you are exploring how to do it. I wouldn't assume we'd accept a pull request and put a lot of time in trying to keep up with the code base or make things perfect, but i am grateful if i can learn from you how to do things for iOS. Nice you are playing with things!

**Comment by makepaddev** [comment]
The whole codebase is going to go through a major restructuring / repo change soon. I'm merging codebases with my cofounder and we are shuffling things around. Fair warning :)

**Comment by makepaddev** [comment]
However 'how the code works' will not be as variable, i dont' have major refactorings planned for cx / the platform API structure however since we'll also be adding android+VR (oculus native SDK) i can't really predict how the platform layer will reshuffle. Hence why i'm saying i generally only accept 'examples to learn from' for now and not promising any kind of stability. But over time this will change of course.

**Comment by rsaccon** [comment]
Great, thanks. I will continue. If I get it working on iOS, I will let you know and post the link to my fork.

**Comment by makepaddev** [comment]
I'm going to close this for inactivity, but feel free to reopen if something happens.

**Comment by makepaddev** [comment]
Hey, saw you subscribe a few times,
We don’t actually have anything in place that will mail you a confirmation. But I’ve seen you enter your address a few times.
Feel free to try more, but you won’t get confirms for a while until we figure out also sending emails nicely.
I think I need to write an SMTP client on a raw socket for that ;)
Thanks for your interest in Makepad!

**Comment by rsaccon** [comment]
Was just playing with the form. Amazing stuff! My iOS support attempt did not get very far (or very far from something usable) but digging into the makepad sources made me permanently interested in Makepad as a potential Rust based cross platform ecosystem with GUI and high performance graphics!

**Comment by makepaddev** [comment]
Thanks :) Yea something as silly as signup form is the hallmark of HTML so replacing that with our own stack is quite some work. I'm actually happy we don't have iOS/android story since i'd rather stay away from mobile 'app' development usecases for a while. Wanna stay with the 'makepad is for fun' angle and see how that goes. But yeah Rust as a stack for high perf UI is shaping up to work better than i could have imagined at the start.

**Comment by not-fl3** [comment]
@rsaccon you might be interested to check out https://github.com/not-fl3/miniquad/blob/master/src/native/ios.rs

it is not super recognizable, but basically it is makepad's appkit code ported to uikit

(yes, it is a very old issue, but still :D)
