### ISSUE TITLE
handle `back` button on android

### ISSUE THREAD

**Issue by univerz** [makepad/makepad#357]
see https://github.com/rust-windowing/winit/issues/2304

**Comment by yulnr** [comment]
I think this one should be fairly straight forward (for android).
We have an [OnBackPressed](https://developer.android.com/reference/android/app/Activity#onBackPressed()) callback on `MainActivity.java`, currently not being used. 
Actually `OnBackPressed` is deprecated on API level > 33 in favor of [OnBackInvoked](https://developer.android.com/reference/android/window/OnBackInvokedCallback). 
I think we could send a message from java to rust when `OnBackInvoked` is called (like we do for `onResume()` and `onStop()`, etc.), and then add a new event (e.g. `BackPressed` or something similar that's generic and re-usable cross-platform). 
With that setup you should be able to handle that event on the apps.

Leaving these details for discussion/implementation in case you or someone else wants to go for it. Otherwise I can come back to this later.

**Comment by yulnr** [comment]
Hey @univerz, PR #403 from @guofoo added support for sending out `BackPressed` events on Android. We'll wire this into `StackNavigation` and others later. For now you should be able to handle the event itself on app/widgets.

**Comment by univerz** [comment]
thank you :)
