### ISSUE TITLE
Add the enter key to the button widget.

### ISSUE THREAD

**Issue by Guocork** [makepad/makepad#565]
This feature comes from Robrix. When Robrix logs in, I want the user to be able to press the enter key after entering their username and password to trigger the login function. However, the button widget doesn't have a corresponding `returned()` method.

**Comment by Guocork** [comment]
I am currently working on fixing this issue.

**Comment by yulnr** [comment]
@Guocork for that issue, wouldn't it make sense to actually use the `returned()` method on the `TextInput` corresponding to the last item in the login section?
Because that is where the user focus would be, also Makepad does not have something like "tab" to move focus between elements. Without focus on the actual UI element you shouldn't assume that it was `returned`.
So maybe the solution could be that as soon as you finish typing your password you hit return without having to switch focus to the Button. Perhaps you can simply use the `returned` method of `TextInputRef`? (`password_input` and `homeserver_input` for your case in Robrix)
