### ISSUE TITLE
Feature request: move the Rendering/widget crates into separate project

### ISSUE THREAD

**Issue by oddcoder** [makepad/makepad#74]
There isn't much gui libs around for rust and the widgets used here looks nice so I would be cool if they could be separated into a standalone crate(s)

**Comment by makepaddev** [comment]
The crates are not 'supported' yet standalone since we haven't stabilised the APIs, however we will push them to crates.io under the names makepad-render makepad-widget. They will remain in this makepad 'github' project as that is the easiest way for us to maintain project coherence. But in the future you can depend on them as crates.io crates. I can't give you hard deadlines yet when we would consider depending on them a good idea, but keep an eye on things for Q1/Q2.
