### ISSUE TITLE
2D Drawing API

### ISSUE THREAD

**Issue by sampaioletti** [makepad/makepad#95]
Hello I've been playing around with the makepad rendering lib and was going to take a stab at a small 2d drawing api (along the lines of canvas) for something I want to try with the lib.

What would be the 'best' way to accomplish draw implementations for the render::vector lib currently the only GL primitive I see in use are Quads.

I'm still new to GL terms/methods so please excuse my ignorance, but would it best to continue to use quads as the primitive for that or implement another primitive like a GL_LINE_STRIP for the compiler.

If you dont mind steering me in the right direction I would appreciate it. Appreciate the great project

**Comment by makepaddev** [comment]
Hi so, unfortunately we have 4 backends and the only primitive exposed is the instanced array indexed triangles. Adding new primitives here is quite a bit of work since you need to thread this through 4 backends. Integrating our vector lib as a proper draw API is still on our todo, but i can't really help you much there yet. This will get easier soon but right now i don't really know what i can do for you.

**Comment by sampaioletti** [comment]
Thanks for the quick response. So I take it the Quad struct is just implemented over the underlaying triangles. That makes sense. I was thinking I was missing something in the library due to my lack of experience with GL.  I'll do some more research knowing that now...thanks again!
